Specify Rails version for migrations
The following message we displayed when running `rails db:migrate` in prod:

```
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class DropDiaries < ActiveRecord::Migration[4.2]
/app/vendor/bundle/ruby/2.6.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:528:in `inherited'
/app/db/migrate/20191113204233_drop_diaries.rb:1:in `<top (required)>'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `require'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:291:in `block in require'
...
```